---
title: "Project Performance Metrics"
author: "Praveen"
date: "April 17, 2018"
output: html_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)


library("ggplot2")
library("dplyr")
library("rpart")
library("partykit")

##Loading the csv Data file:

raw_data <- read.csv('C:\\Users\\PraveenChander\\Desktop\\pySparking\\Class 2 - Data Science Principles and Practice\\practice\\bank.csv', header = T,sep = ';')
head(raw_data)

# plot the relationship between Age and the Subscription y (Bar Graph)
raw_data %>% 
ggplot() + 
  geom_bar(aes(x = age, y = y), stat = 'identity') +
  labs(x="Age", y="Subscription") +
  theme_bw()
# plot the relationship between Marital and the Subscription y (Bar Graph)
raw_data %>% 
ggplot() + 
  geom_bar(aes(x = marital, y = y), stat = 'identity') +
  labs(x="marital", y="Subscription") +
  theme_bw()

# plot the relationship between Education and the Subscription y (Bar Graph)
raw_data %>% 
ggplot() + 
  geom_bar(aes(x = education, y = y), stat = 'identity') +
  labs(x="Education", y="Subscription") +
  theme_bw()


# plot the relationship between Job and the Subscription y (Bar Graph)
raw_data %>% 
ggplot() + 
  geom_bar(aes(x = job, y = y), stat = 'identity') +
  labs(x="Job", y="Subscription") +
  theme_bw()

#Sampling the data into 2 sets from the csv file:

ind <- sample(2,nrow(raw_data), replace = TRUE, prob = c(0.8,0.2))
train_data <- raw_data[ind==1,]
test_data <- raw_data[ind==2,]
library(randomForest)


##Random Forest Model Fitting with Training Sample:

model <- randomForest(y ~ age + job + marital + education + balance + default + housing + loan + contact + duration + campaign + pdays + previous + poutcome, data = train_data)
print(model)

##Model Fitting with Test Sample:

model <- randomForest(y ~ age + job + marital + education + balance + default + housing + loan + contact + duration + campaign + pdays + previous + poutcome, data = test_data)
print(model)

#  Generate Logistic Regression model

glm_mod <- glm(y~age + job + marital+education+default+balance+housing+loan+contact+duration+campaign+pdays+previous+poutcome,data=train_data,family=binomial())
summary(glm_mod) # display results
confint(glm_mod) # 95% CI for the coefficients
exp(coef(glm_mod)) # exponentiated coefficients
exp(confint(glm_mod)) # 95% CI for exponentiated coefficients
predict(glm_mod, type="response") # predicted values
residuals(glm_mod, type="deviance") # residuals

tree_mod <- rpart(y ~ age + job + marital+education+default+balance+housing+loan+contact+duration+campaign+pdays+previous+poutcome,data=train_data)
# plot the tree
plot(as.party(tree_mod))
